### ISSUE TITLE
can't install it ???

### ISSUE THREAD

**Issue by lancezhangsf** [qitianchan/lorawan-for-python#1]
Hi:

i can't install it ,show as follws:

Installed c:\python27\lib\site-packages\python_lorawan-0.9.0-py2.7.egg
Processing dependencies for python-lorawan==0.9.0
Searching for pyaes>=1.3.0
Reading https://pypi.python.org/simple/pyaes/
Download error on https://pypi.python.org/simple/pyaes/: [Errno 11004] getaddrinfo failed -- Some packages may not be found!
Couldn't find index page for 'pyaes' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 11004] getaddrinfo failed -- Some packages may not be found!
No local packages or download links found for pyaes>=1.3.0
error: Could not find suitable distribution for Requirement.parse('pyaes>=1.3.0')

**Comment by qitianchan** [comment]
I'm so sorry for that I have not continue for this work for some reason
